# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sshm < Formula
  desc "SSH key and config manager"
  homepage "https://github.com/biva8710/my-go-bin"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/biva8710/my-go-bin/releases/download/v0.1.0/sshm_0.1.0_darwin_amd64.tar.gz"
      sha256 "8133ce941f57cab986f3438a7ce9b59c361808cc40538cb5efa5702df43611a2"

      define_method(:install) do
        bin.install "sshm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/biva8710/my-go-bin/releases/download/v0.1.0/sshm_0.1.0_darwin_arm64.tar.gz"
      sha256 "2d9a957b8011cd6440fcd87ab7fef4e7db341a453b8862536f23213f4b1b536b"

      define_method(:install) do
        bin.install "sshm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/biva8710/my-go-bin/releases/download/v0.1.0/sshm_0.1.0_linux_amd64.tar.gz"
      sha256 "f5b2c1a17f5ae68b5e031c2ea803796269873218ec54b597ea4e1f364eabd4f1"
      define_method(:install) do
        bin.install "sshm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/biva8710/my-go-bin/releases/download/v0.1.0/sshm_0.1.0_linux_arm64.tar.gz"
      sha256 "5d11e5320fac1b0af650b0011bdd839df4ff2259e7c20d2d11c9aa2a8517945d"
      define_method(:install) do
        bin.install "sshm"
      end
    end
  end
end
